# Form implementation generated from reading ui file 'create_cert.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Create_CERT(object):
    def setupUi(self, creating_dialog):
        creating_dialog.setObjectName("Dialog")
        creating_dialog.resize(400, 300)
        self.Dialog = creating_dialog
        self.buttonBox = QtWidgets.QDialogButtonBox(creating_dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(creating_dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(creating_dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 361, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(creating_dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(creating_dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 60, 16))
        self.label_4.setObjectName("label_4")
        self.textEditName = QtWidgets.QTextEdit(creating_dialog)
        self.textEditName.setGeometry(QtCore.QRect(60, 110, 301, 21))
        self.textEditName.setObjectName("textEditName")
        self.textEditEmail = QtWidgets.QTextEdit(creating_dialog)
        self.textEditEmail.setGeometry(QtCore.QRect(60, 140, 301, 21))
        self.textEditEmail.setObjectName("textEditEmail")
        #self.label_5 = QtWidgets.QLabel(creating_dialog)
        #self.label_5.setGeometry(QtCore.QRect(70, 170, 291, 20))
        #self.label_5.setObjectName("label_5")
        #self.checkBoxPassphrase = QtWidgets.QCheckBox(creating_dialog)
        #self.checkBoxPassphrase.setGeometry(QtCore.QRect(50, 170, 87, 20))
        #self.checkBoxPassphrase.setText("")
        #self.checkBoxPassphrase.setObjectName("checkBoxPassphrase")
        self.additional = QtWidgets.QPushButton(creating_dialog)
        self.additional.setGeometry(QtCore.QRect(20, 235, 130, 40))
        self.additional.setText("Additional settings")

        self.label_addition = QtWidgets.QLabel(creating_dialog)
        self.label_addition.setGeometry(QtCore.QRect(100, 220, 130, 16))
        self.label_addition.setObjectName("label_addition")
        self.label_addition.setHidden(True)

        self.choose_curve_name = QtWidgets.QComboBox(creating_dialog)
        self.choose_curve_name.setGeometry(QtCore.QRect(150, 250, 111, 26))
        self.choose_curve_name.setObjectName("choose_curve_name")
        self.choose_curve_name.addItem("")
        self.choose_curve_name.addItem("")
        self.choose_curve_name.addItem("")
        self.choose_curve_name.addItem("")
        self.choose_curve_name.setHidden(True)

        self.choose_mode = QtWidgets.QComboBox(creating_dialog)
        self.choose_mode.setGeometry(QtCore.QRect(150, 290, 101, 26))
        self.choose_mode.setObjectName("choose_mode")
        self.choose_mode.addItem("")
        self.choose_mode.addItem("")
        self.choose_mode.addItem("")
        self.choose_mode.setHidden(True)

        self.label_curve = QtWidgets.QLabel(creating_dialog)
        self.label_curve.setGeometry(QtCore.QRect(10, 250, 130, 16))
        self.label_curve.setObjectName("label_curve")
        self.label_curve.setHidden(True)

        self.label_mode = QtWidgets.QLabel(creating_dialog)
        self.label_mode.setGeometry(QtCore.QRect(10, 290, 130, 16))
        self.label_mode.setObjectName("label_mode")
        self.label_mode.setHidden(True)


        self.retranslateUi(creating_dialog)
        

        self.buttonBox.accepted.connect(creating_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(creating_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(creating_dialog)
        self.flag_additional = False
        
        self.additional.clicked.connect(self.change_enable_additional)
        self.choose_mode.currentTextChanged.connect(self.updateComboValueMode)
        self.choose_curve_name.currentTextChanged.connect(self.updateComboValueCurve)
        self.combo_value_mode = "CBC"
        self.combo_value_curve = "secp256k1"
        


    def saveText(self):
        return self.textEditName.toPlainText(), self.textEditEmail.toPlainText(), self.combo_value_curve, self.combo_value_mode


    def updateComboValueMode(self, text):
        self.combo_value_mode = text
        

    def updateComboValueCurve(self, text):
        self.combo_value_curve = text
      



    def change_enable_additional(self):
        if self.flag_additional is False:
            self.flag_additional = True
            self.Dialog.resize(400, 400)
            self.buttonBox.setGeometry(QtCore.QRect(30, 350, 341, 32))
            self.additional.setGeometry(QtCore.QRect(20, 340, 130, 40))
            self.choose_curve_name.setHidden(False)
            self.choose_mode.setHidden(False)
            self.label_addition.setHidden(False)
            self.label_curve.setHidden(False)
            self.label_mode.setHidden(False)
        else:
            self.flag_additional = False
            self.Dialog.resize(400, 300)
            self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
            self.additional.setGeometry(QtCore.QRect(20, 235, 130, 40))
            self.choose_curve_name.setHidden(True)
            self.choose_mode.setHidden(True)
            self.label_addition.setHidden(True)
            self.label_curve.setHidden(True)
            self.label_mode.setHidden(True)





    def retranslateUi(self, creating_dialog):
        _translate = QtCore.QCoreApplication.translate
        creating_dialog.setWindowTitle(_translate("Dialog", "Creating Certificate"))
        self.label.setText(_translate("Dialog", "Enter Details"))
        self.label_2.setText(_translate("Dialog", "Please enter personal details below."))
        self.label_3.setText(_translate("Dialog", "Name:"))
        self.label_4.setText(_translate("Dialog", "E-mail:"))
        #self.label_5.setText(_translate("Dialog", "Protect the generated key with a passphrase."))
        self.additional.setText(_translate("Dialog", "Additional settings"))

        self.choose_curve_name.setItemText(0, _translate("Dialog", "secp256k1"))
        self.choose_curve_name.setItemText(1, _translate("Dialog", "secp160k1"))
        self.choose_curve_name.setItemText(2, _translate("Dialog", "secp192k1"))
        self.choose_curve_name.setItemText(3, _translate("Dialog", "secp224k1"))

        
        self.choose_mode.setItemText(0, _translate("Dialog", "CBC"))
        self.choose_mode.setItemText(1, _translate("Dialog", "CFB"))
        self.choose_mode.setItemText(2, _translate("Dialog", "OFB"))
        #self.choose_mode.setItemText(3, _translate("Dialog", "CRT"))
        #self.choose_mode.setItemText(4, _translate("Dialog", "EAX"))
        
        self.label_addition.setText(_translate("Dialog", "Additional settings:"))
        self.label_curve.setText(_translate("Dialog", "Choose curve name:"))
        self.label_mode.setText(_translate("Dialog", "Choose AES mode:"))

       


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Create_CERT()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
