# Form implementation generated from reading ui file 'passphrase.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UiCreatePassphrase(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 288)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 111, 16))
        self.label_2.setObjectName("label_2")

        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(150, 60, 231, 21))
        self.password.setObjectName("password")
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)

        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 121, 16))
        self.label_3.setObjectName("label_3")

        self.confirm_password = QtWidgets.QLineEdit(Dialog)
        self.confirm_password.setGeometry(QtCore.QRect(150, 120, 231, 21))
        self.confirm_password.setObjectName("confirm_password")
        self.confirm_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)


        self.checkBox_4 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_4.setGeometry(QtCore.QRect(270, 90, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_5.setGeometry(QtCore.QRect(270, 150, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.add_fun()

   

    def add_fun(self):
        self.checkBox_4.clicked.connect(lambda: self.change_password_visibility(self.checkBox_4, self.password))
        self.checkBox_5.clicked.connect(lambda: self.change_password_visibility(self.checkBox_5, self.confirm_password ))
        self.buttonBox.clicked.connect(self.saveText)
    
    
    def saveText(self):
        if self.password.text() == self.confirm_password.text():
            return self.password.text() 
        QtWidgets.QMessageBox.information(
        self.Dialog, "Passwords don`t match", "Passwords don`t match", 
        QtWidgets.QMessageBox.StandardButton.Ok)

    def change_password_visibility(self, chckbox, passwordedit):
        if chckbox.isChecked():
            passwordedit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        else:
            passwordedit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Enter passphrase"))
        self.label_3.setText(_translate("Dialog", "Confirm passphrase"))
        self.checkBox_4.setText(_translate("Dialog", "show password"))
        self.checkBox_5.setText(_translate("Dialog", "show password"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = UiCreatePassphrase()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
