# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Registrate_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(160, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 121, 16))
        self.label_4.setObjectName("label_4")
        self.email = QtWidgets.QLineEdit(Dialog)
        self.email.setGeometry(QtCore.QRect(130, 60, 241, 21))
        self.email.setObjectName("lineEdit")
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(130, 90, 241, 21))
        self.password.setObjectName("lineEdit_2")
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)

        self.password_confirm = QtWidgets.QLineEdit(Dialog)
        self.password_confirm.setGeometry(QtCore.QRect(130, 150, 241, 21))
        self.password_confirm.setObjectName("lineEdit_3")
        self.password_confirm.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)


        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(260, 120, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(260, 180, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.add_fun()

    def add_fun(self):
        self.checkBox.clicked.connect(lambda: self.change_password_visibility(self.checkBox, self.password))
        self.checkBox_2.clicked.connect(lambda: self.change_password_visibility(self.checkBox_2, self.password_confirm))
        self.buttonBox.clicked.connect(self.saveText)
    
    
    def saveText(self):
        return self.email.text(), self.password.text()

    def change_password_visibility(self, chckbox, passwordedit):
        if chckbox.isChecked():
            passwordedit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        else:
            passwordedit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Registration Form"))
        self.label.setText(_translate("Dialog", "Registration"))
        self.label_2.setText(_translate("Dialog", "User name / email:"))
        self.label_3.setText(_translate("Dialog", "Password:"))
        self.label_4.setText(_translate("Dialog", "Confirm Password:"))
        self.checkBox.setText(_translate("Dialog", "show password"))
        self.checkBox_2.setText(_translate("Dialog", "show password"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Registrate_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())

